### ISSUE TITLE
Support for ADFS fields

### ISSUE THREAD

**Issue by bartjkdp** [Project-Meerkat/concierge#60]
I thought we looked into this already, but ADFS (a SAML2 identity provider) by default offers a set of claims that can be configured and the names are difficult to change. These names are different then the claims expected by concierge. This is an example claimset offered by ADFS:

```
saml.views.acs, number of attributes: 4
saml.views.acs, attribute: ('http://schemas.xmlsoap.org/ws/2005/05/identity/claims/name', ['Bart'])
saml.views.acs, attribute: ('http://schemas.xmlsoap.org/ws/2005/05/identity/claims/emailaddress', ['bart@pleio.nl'])
saml.views.acs, attribute: ('http://schemas.xmlsoap.org/ws/2005/05/identity/claims/upn', ['bart@pleio.lan'])
saml.views.acs, attribute: ('http://schemas.microsoft.com/ws/2008/06/identity/claims/windowsaccountname', ['bart'])
saml.views.connect,  no emailaddress in samlUserdata found
```

Currently we experience some challenges with linking organisations with ADFS. It would be nice if we are able to use these claims as well by default, so a translation from `http://schemas.xmlsoap.org/ws/2005/05/identity/claims/name` to `name` and `http://schemas.xmlsoap.org/ws/2005/05/identity/claims/emailaddress` to `emailaddress`.

**Comment by AadSchippers** [comment]
Sorted in commit **[Sorted SAML issues #60 and 61](https://github.com/Project-Meerkat/concierge/commit/1493b35dfe42d7d9083e13d1ae79844af804811e)**
