### ISSUE TITLE
The metadata endpoint is dependent on filesystem for constructing response

### ISSUE THREAD

**Issue by bartjkdp** [Project-Meerkat/concierge#61]
In the views.py of the SAML plugin the metadata endpoint is dependent on the filesystem for constructing a response, see:

https://github.com/Project-Meerkat/concierge/blob/202aa4cf5365b41029c4c10fc7fcec91a18117df/saml/views.py#L205-L214

This introduces the ability for race conditions as a Django application in production is usually multi-threaded. It would be better to remove the `settings.SAML_FOLDER` attribute and just use dicts for configuring OneLogin_Saml2, like [here](https://github.com/Project-Meerkat/concierge/blob/a0b99527c2dca1b0097d7aa3d48cf9cd35f3f619/saml/views.py#L43).

**Comment by AadSchippers** [comment]
Sorted in commit **[Sorted SAML issues #60 and 61](https://github.com/Project-Meerkat/concierge/commit/1493b35dfe42d7d9083e13d1ae79844af804811e)**
