### ISSUE TITLE
Admin: Extend user fields in overview

### ISSUE THREAD

**Issue by bartjkdp** [Project-Meerkat/concierge#62]
Would be nice if the user overview contains the following information:

- id
- name
- email

**Comment by bartjkdp** [comment]
Never mind, was an incomplete user object.

**Comment by AadSchippers** [comment]
Sorted in commit **[Sorted issue #62. Also added SAML ExternalIds to admin User panel](https://github.com/Project-Meerkat/concierge/commit/ba749e8bce3bf895f361f03601c871ed05dca011)**
