### ISSUE TITLE
It is possible to register two accounts with the same e-mailaddress (but with different casing)

### ISSUE THREAD

**Issue by bartjkdp** [Project-Meerkat/concierge#64]
It is now possible to register to e-mailddresses with the same e-mailadress but different casing, e.g.:

- test@test.com
- tesT@test.com

Would be nice to transform e-mails always to lowercase when stored, so string comparison can be done easily.

**Comment by AadSchippers** [comment]
Hmmm, this looks it's a feature by design:
```
class BaseUserManager(models.Manager):

    @classmethod
    def normalize_email(cls, email):
        """
        Normalize the email address by lowercasing the domain part of it.
        """
        email = email or ''
        try:
            email_name, domain_part = email.strip().rsplit('@', 1)
        except ValueError:
            pass
        else:
            email = '@'.join([email_name, domain_part.lower()])
        return email
```

**Comment by bartjkdp** [comment]
In this code only the domain part gets lowercased... this allows a user to register multiple accounts with the same e-mailaddress.

**Comment by bartjkdp** [comment]
@lucbelliveau @bryan-robitaille is there any reason only the domain part is case-insensitive? Would you agree to make the whole e-mail address case-insensitive?

**Comment by lucbelliveau** [comment]
I think the the comparison function to determine if an email can be registered should lowercase... even if you enforce all lowercase emails... Same thing for the authentication query + login code... to prevent potential attack vectors.

I suspect the casing was preserved for legibility (First-Name.Lastname@...) Is that correct @bryan-robitaille ?  Even if it is not required, I would still recommending explicitly converting to a known case during processing...   Any migration should also check for existing duplicates...  hopefully there are not too many.

**Comment by AadSchippers** [comment]
This is sorted in **[Stored email adresses all in lowercase, ignoring case on forms](https://github.com/Project-Meerkat/concierge/commit/63ce068cb24b878da0b94791e61ed68174f91777)**
