### ISSUE TITLE
Users without password are not migrated correctly

### ISSUE THREAD

**Issue by bartjkdp** [Project-Meerkat/concierge#66]
When a user has no password in Elgg (password_hash column is empty), the system still sets some content for the password field:

```
bcrypt$
```

I think we should set this field to NULL or generate a password randomly for these users.

(This also is the reason why some users do not display correctly in the admin panel)

**Comment by AadSchippers** [comment]
This is sorted in commit **[Data migration script migrated. Sorted issues #66 and #67](https://github.com/Project-Meerkat/concierge/commit/b1746988a35e6424d354620f4b70cd8101eb6a4b)**
