### ISSUE TITLE
Make SAML login workable for every NameID type

### ISSUE THREAD

**Issue by bartjkdp** [Project-Meerkat/concierge#68]
Right now we always use the emailaddress as an attribute to link Pleio accounts with IdP accounts. It would be nice to make this more generic, so the Identity Provider can choose which attribute they want to provide to link accounts (e.g. also a username or a unique ID).

We can change this code: 

https://github.com/Project-Meerkat/concierge/blob/5e23595b143bb3a55119dd8ab9bbebef63ed30d6/saml/views.py#L110

And use the `get_nameid()` function to retrieve the name ID specified by the Identity Provider, see https://github.com/onelogin/python3-saml

We should also make the NameIDFormat more generic, we could change this to `urn:oasis:names:tc:SAML:2.0:nameid-format:persistent` instead of specific e-mailaddress.

https://github.com/Project-Meerkat/concierge/blob/538c0537451c594f1f1d5b00a820156affbef4ef/docker/config.py#L104

Also we should not forget to update the template in `/saml/connections/`.

**Comment by bartjkdp** [comment]
In Pleio/concierge@c97db90 I already set NameIDFormat to persistent, because I already needed this when creating a link with a certain SAML IdP.

**Comment by AadSchippers** [comment]
This is sorted in **[added support for connecting a saml:nameid as externalid](https://github.com/Project-Meerkat/concierge/commit/2506b34a918fbe4b99f43e0078e1a1160bfc25c3)**
