### ISSUE TITLE
The /mod/profile/icondirect.php endpoint throws 500's when users cannot be found

### ISSUE THREAD

**Issue by bartjkdp** [Project-Meerkat/concierge#71]
When requesting an avatar for a user that does not exist (e.g. `https://account.pleio.nl/mod/profile/icondirect.php?guid=26690102&size=large&lastcache=1533635027`), the server throws a 500 error.

It would be a lot nicer to just give back an avatar of an empty user: https://github.com/Pleio/pleio/blob/master/mod/pleio_template/src/images/user.png

**Comment by AadSchippers** [comment]
Sorted in commit **[Sorted bug when serving an avatar for a user that does not exist, problem #71](https://github.com/Project-Meerkat/concierge/commit/e0bfe18bd12adca9b63f4c4b984689f87abfee52)**
