### ISSUE TITLE
SAML errors not visible on frontend

### ISSUE THREAD

**Issue by bartjkdp** [Project-Meerkat/concierge#72]
When a SAML login attempt fails (because of a technical error) there is no feedback at all to the end user. It would be great to not only log errors like these in the application log, but also provide user with an error message, with a small technical explanation (e.g. invalid_response) that allows the technical people to further debug the issue.

```
[pid: 42|app: 0|req: 40/192] 10.1.4.0 () {60 vars in 1352 bytes} [Thu Sep  6 11:27:50 2018] POST /get_user_and_idp/ =&gt; generated 40 bytes in 19 msecs (HTTP/1.1 200) 9 headers in 572 bytes (1 switches on core 0)
saml.views.acs, errors found: ['invalid_response']reason: Signature validation failed. SAML Response rejected
```

**Comment by AadSchippers** [comment]
**[Sorted SAML errors not visible on frontend #72](https://github.com/Project-Meerkat/concierge/commit/e92ff0284b0adc29d86f7130f33c56bc93004780)**

**Comment by bartjkdp** [comment]
Thanks!
